"""add playroom tables

Rooms, players, rounds and the Bingo per-game tables, plus the append-only
event log the analytics questions are answered from.

Written by hand rather than autogenerated. Three things here autogenerate does
not produce correctly: the partial unique index on a room key, the functional
partial unique index on a nickname, and the seed rows for the game catalogue.

The DDL is dialect-neutral on purpose. Production is Neon (PostgreSQL) but the
tests, local development and the CI container smoke test all run SQLite, so the
same migration has to apply to both. `sa.Uuid` is a native `uuid` on PostgreSQL
and `CHAR(32)` on SQLite; `sa.JSON().with_variant(JSONB, ...)` is `jsonb` on
PostgreSQL and `JSON` text on SQLite.

Revision ID: a1f3c7d90b21
Revises: d227d179c2a9
Create Date: 2026-09-09 18:05:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "a1f3c7d90b21"
down_revision: str | None = "d227d179c2a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: jsonb where it exists, JSON text on SQLite.
JSON_COLUMN = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")
#: SQLite only auto-increments a column declared exactly `INTEGER PRIMARY KEY`.
AUTO_BIGINT = sa.BigInteger().with_variant(sa.Integer(), "sqlite")
NOW = sa.text("(CURRENT_TIMESTAMP)")


def upgrade() -> None:
    op.create_table(
        "playroom_games",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("min_players", sa.SmallInteger(), nullable=False),
        sa.Column("max_players", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "playroom_rooms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("game_id", sa.String(length=32), nullable=False),
        sa.Column("host_player_id", sa.Uuid(), nullable=True),
        sa.Column("phase", sa.String(length=16), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("settings", JSON_COLUMN, nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["playroom_games.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # A key is unique among ACTIVE rooms only. Expired rooms keep their key for
    # analytics and the key becomes reusable. The predicate must be immutable,
    # so the sweeper flips `status` rather than the index reading now().
    op.create_index(
        "playroom_rooms_active_key",
        "playroom_rooms",
        ["key"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "playroom_rooms_expiry",
        "playroom_rooms",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
        sqlite_where=sa.text("status = 'active'"),
    )

    op.create_table(
        "playroom_players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("avatar_color", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("is_host", sa.Boolean(), nullable=False),
        sa.Column("seat", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["room_id"], ["playroom_rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # Nicknames are unique within one LIVE room only, case-insensitive. A player
    # who leaves frees theirs.
    op.create_index(
        "playroom_players_room_name",
        "playroom_players",
        ["room_id", sa.text("lower(display_name)")],
        unique=True,
        postgresql_where=sa.text("left_at IS NULL"),
        sqlite_where=sa.text("left_at IS NULL"),
    )
    op.create_index(
        "playroom_players_room_seat", "playroom_players", ["room_id", "seat"], unique=True
    )
    op.create_index("playroom_players_token", "playroom_players", ["token_hash"], unique=False)

    op.create_table(
        "playroom_rounds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.String(length=32), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("turn_order", JSON_COLUMN, nullable=False),
        sa.Column("current_turn_index", sa.Integer(), nullable=False),
        sa.Column("winner_player_id", sa.Uuid(), nullable=True),
        sa.Column("win_detail", JSON_COLUMN, nullable=True),
        sa.Column("state", JSON_COLUMN, nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["playroom_games.id"]),
        sa.ForeignKeyConstraint(["room_id"], ["playroom_rooms.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "playroom_rounds_room_number",
        "playroom_rounds",
        ["room_id", "round_number"],
        unique=True,
    )

    op.create_table(
        "playroom_bingo_boards",
        sa.Column("round_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("cells", JSON_COLUMN, nullable=True),
        sa.ForeignKeyConstraint(["player_id"], ["playroom_players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["round_id"], ["playroom_rounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("round_id", "player_id"),
    )

    # The composite primary key is not decoration. It is how the database — not
    # application code — guarantees two players never take the same number.
    op.create_table(
        "playroom_bingo_selections",
        sa.Column("round_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.CheckConstraint("number BETWEEN 1 AND 25", name="playroom_bingo_selections_range"),
        sa.ForeignKeyConstraint(["round_id"], ["playroom_rounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("round_id", "number"),
    )
    op.create_index(
        "playroom_bingo_selections_seq",
        "playroom_bingo_selections",
        ["round_id", "seq"],
        unique=True,
    )

    op.create_table(
        "playroom_events",
        sa.Column("id", AUTO_BIGINT, autoincrement=True, nullable=False),
        sa.Column("room_id", sa.Uuid(), nullable=True),
        sa.Column("round_id", sa.Uuid(), nullable=True),
        sa.Column("player_id", sa.Uuid(), nullable=True),
        sa.Column("game_id", sa.String(length=32), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("payload", JSON_COLUMN, nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("playroom_events_room", "playroom_events", ["room_id", "id"], unique=False)
    op.create_index(
        "playroom_events_type_time", "playroom_events", ["type", "occurred_at"], unique=False
    )
    op.create_index(
        "playroom_events_game_time", "playroom_events", ["game_id", "occurred_at"], unique=False
    )

    op.create_table(
        "playroom_idempotency_keys",
        sa.Column("round_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("response", JSON_COLUMN, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=NOW, nullable=False),
        sa.ForeignKeyConstraint(["round_id"], ["playroom_rounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("round_id", "key"),
    )

    op.create_table(
        "playroom_daily_game_stats",
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("game_id", sa.String(length=32), nullable=False),
        sa.Column("rooms_created", sa.Integer(), nullable=False),
        sa.Column("rounds_played", sa.Integer(), nullable=False),
        sa.Column("distinct_players", sa.Integer(), nullable=False),
        sa.Column("median_round_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("day", "game_id"),
    )

    # The catalogue. `status` is `playable` only where a game engine exists, so
    # a host cannot open a room for a game that cannot be played. Promoting one
    # is a data change plus an engine, never a data change alone.
    op.bulk_insert(
        sa.table(
            "playroom_games",
            sa.column("id", sa.String),
            sa.column("name", sa.String),
            sa.column("status", sa.String),
            sa.column("min_players", sa.SmallInteger),
            sa.column("max_players", sa.SmallInteger),
        ),
        [
            {
                "id": "bingo",
                "name": "Bingo",
                "status": "playable",
                "min_players": 2,
                "max_players": 20,
            },
            {
                "id": "scribble",
                "name": "Scribble",
                "status": "building",
                "min_players": 4,
                "max_players": 12,
            },
            {
                "id": "ttt",
                "name": "Tic-tac-toe",
                "status": "building",
                "min_players": 2,
                "max_players": 2,
            },
        ],
    )


def downgrade() -> None:
    op.drop_table("playroom_daily_game_stats")
    op.drop_table("playroom_idempotency_keys")
    op.drop_index("playroom_events_game_time", table_name="playroom_events")
    op.drop_index("playroom_events_type_time", table_name="playroom_events")
    op.drop_index("playroom_events_room", table_name="playroom_events")
    op.drop_table("playroom_events")
    op.drop_index("playroom_bingo_selections_seq", table_name="playroom_bingo_selections")
    op.drop_table("playroom_bingo_selections")
    op.drop_table("playroom_bingo_boards")
    op.drop_index("playroom_rounds_room_number", table_name="playroom_rounds")
    op.drop_table("playroom_rounds")
    op.drop_index("playroom_players_token", table_name="playroom_players")
    op.drop_index("playroom_players_room_seat", table_name="playroom_players")
    op.drop_index("playroom_players_room_name", table_name="playroom_players")
    op.drop_table("playroom_players")
    op.drop_index("playroom_rooms_expiry", table_name="playroom_rooms")
    op.drop_index("playroom_rooms_active_key", table_name="playroom_rooms")
    op.drop_table("playroom_rooms")
    op.drop_table("playroom_games")
